name: Run Tests

# Trigger the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run tests
      run: |
        python -m unittest discover -s tests
        coverage run --source=src -m unittest discover -s tests
    - name: Generate coverage report
      run: |
        coverage report
        coverage html
